mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views
from order import views  as orderViews
from user import views  as userViews
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('product/', include('product.urls')),
    path('order/', include('order.urls')),
    path('user/', include('user.urls')),
    path('about/', views.aboutus, name='about'),
    path('contact/', views.contactus, name='contact'),
    path('category/<int:id>/<slug:slug>', views.category_product, name='category'),
    path('search/', views.search, name='searchProduct'),
    path('searchAuto/', views.searchAuto, name='searchAuto'),
    path('product/<int:id>/<slug:slug>', views.productDetail, name='productDetail'),
    path('shopcart/', orderViews.shopCart, name='shopCart'),
    path('login/', userViews.loginForm, name='login'),
    path('logout/', userViews.logoutFun, name='logout'),
    path('signup/', userViews.signupForm, name='signup'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




    

order/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('addToShopCart/<int:id>', views.addToShopCart, name='addToShopCart'),
    path('deletefromcart/<int:id>', views.deleteFromCart, name='deleteFromCart'),
    path('orderproduct/', views.orderProduct, name='orderProduct'),
]

user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('update/', views.userUpdate, name='update'),
    path('password/', views.userPassword, name='password'),
    path('order/', views.userOrder, name='order'),
    path('orderdetail/<int:id>', views.userOrderDetail, name='orderDetail'),
    path('orderproduct/', views.userOrderProduct, name='orderProduct'),
    path('orderproductdetail/<int:id>/<int:oid>', views.userOrderProductDetail, name='orderProductDetail'),
    path('comment/', views.userComment, name='comment'),
    path('deletecomment/<int:id>', views.userDeleteComment, name='deleteComment'),
]

order/models.py
from django.db import models
from django.contrib.auth.models import User
from product.models import Product
from django.forms import ModelForm

# Create your models here.

class ShopCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField()
    
    def __str__(self):
        return self.product.title
    @property
    def price(self):
        return self.product.price
    
    @property
    def amount(self):
        return (self.quantity * self.product.price)
    
    
class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity']
        
class Order(models.Model):
    STATUS = (
        ('NEW', 'NEW'),
        ('Accepted', 'Accepted'),
        ('Preparing', 'Preparing'),
        ('OnShipping', 'OnShipping'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=5, editable=False)
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    phone = models.CharField(max_length=20, blank=True)
    address = models.CharField(max_length=150, blank=True)
    city = models.CharField(max_length=20, blank=True)
    country = models.CharField(max_length=20, blank=True)
    total = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(max_length=20, blank=True)
    adminnote = models.CharField(max_length=100, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name
    
class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'address','phone', 'city', 'country']


class OrderProduct(models.Model):
    STATUS = (
        ('NEW', 'NEW'),
        ('Accepted', 'Accepted'),
        ('Canceled', 'Canceled'),
    )
    
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.title

    
    
    

order/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from order.models import ShopCart, ShopCartForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from home.models import Setting
from product.models import Category, Product
from user.models import UserProfile
from order.models import OrderForm, Order, OrderProduct
from django.utils.crypto import get_random_string



def index(request):
    return HttpResponse('Order')

@login_required(login_url='/login')  #check user login or not
def addToShopCart(request, id):
    url = request.META.get('HTTP_REFERER') #get the last url0
    current_user = request.user #access user session information

    check_product = ShopCart.objects.filter(product_id= id)
    if check_product:
        control = 1  #the product is in the cart
    else:
        control = 0 #the product is not in the cart
        
    if request.method == 'POST':
        form = ShopCartForm(request.POST)
        if form.is_valid():
            if control==1 :  #update shopcart
                data = ShopCart.objects.get(product_id = id)
                data.quantity += form.cleaned_data['quantity']
                data.save()
            else:  #insert to shopcart
                data = ShopCart()
                data.user_id = current_user.id
                data.product_id = id
                data.quantity = form.cleaned_data['quantity']
                data.save()
        messages.success(request, 'Product added to ShopCart')
        return HttpResponseRedirect(url)
    else: #if there is no post
        if control == 1:
            data = ShopCart.objects.get(product_id = id)
            data.quantity += 1
            data.save()
        else:
            data = ShopCart()
            data.user_id = current_user.id
            data.product_id = id
            data.quantity = 1
            data.save()
        messages.success(request, 'Product added to ShopCart')
        return HttpResponseRedirect(url)
            
        
            
def shopCart(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id = current_user)
    total = 0
    for pro in shopcart:
        total += pro.product.price* pro.quantity
        
    context = {
        'setting' : setting,
        'category' : category,
        'shopcart' : shopcart,
        'total' : total,
    }
    return render(request, 'shopCartProduct.html', context)
    
@login_required(login_url='/login')   
def deleteFromCart(request, id):
    ShopCart.objects.filter(id=id).delete()
    messages.success(request, 'Your item delete from Shopcart')
    return HttpResponseRedirect('/shopcart')


def orderProduct(request):
    category = Category.objects.all()
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    total = 0
    for k in shopcart :
        total += k.product.price * k.quantity
        
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            # send credit cart to bank 
            # if the bank responds ok continue, if not show the error
            data = Order()
            data.first_name = form.cleaned_data['first_name']
            data.last_name = form.cleaned_data['last_name']
            data.address = form.cleaned_data['address']
            data.city = form.cleaned_data['city']
            data.phone = form.cleaned_data['phone']
            data.user_id = current_user.id
            data.total = total
            data.ip = request.META.get('REMOTE_ADDR')
            ordercode = get_random_string(5).upper()  #rand code
            data.code = ordercode
            data.save()
            #move Shopcart item to Order Products Item
            shopcart = ShopCart.objects.filter(user_id=current_user.id)
            print('Testing OrderProduct')
            for k in shopcart:
                detail = OrderProduct()
                detail.order_id = data.id # order id
                print(detail.order_id)
                detail.product_id = k.product_id
                print(detail.product_id)
                detail.user_id = current_user.id
                detail.quantity = k.quantity
                detail.price = k.product.price
                detail.amount = k.amount
                detail.save()
                #reduce quantity of sold product from amount of Product
                product = Product.objects.get(id=k.product_id)
                product.amount -= k.quantity
                product.save()
                
            ShopCart.objects.filter(user_id=current_user.id).delete() #clear and delete form Shopcart
            request.session['cart_items'] = 0
            messages.success(request, 'Your order has been completed. Thank You')
            context = {
                'ordercode' : ordercode,
                'category' : category,
            }
            return render(request, 'orderCompleted.html', context)
        else:
            messages.warning(request, form.errors)
            return HttpResponseRedirect('/order/orderproduct')
    profile = UserProfile.objects.get(user_id=current_user.id)
    form = OrderForm()
    context = {
        'category' : category,
        'shopcart' : shopcart,
        'total' : total,
        'profile' : profile,
    }
    return render(request, 'orderForm.html', context)

order/templates/orderCompleted.html
{% extends 'homebase.html' %}

{% block title %} Order Completed {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

    <!-- BREADCRUMB -->
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">Order Completed</li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div  class="row">

                <div class="col-md-12">
                    <div class="order-summary clearfix">
                        <div class="section-title">
                            <h3 class="title">Order Completed/h3>
                        </div>
                            <hr>
                            <h2>Dear {{user.first_name}} {{user.last_name}}</h2>
                            <hr>
                            <h3>Your order is completed</h3>
                            <h3>Order Code: {{ordercode}}</h3>
                            <h3>Thank You</h3>
                            <hr>
                            

                    </div>

                </div>


            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock %}

order/templates/orderForm.html
{% extends 'homebase.html' %}

{% block title %} Order Page {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

    <!-- BREADCRUMB -->
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">Order Page</li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div  class="row">
                <Form action="" method="post">
                    {% csrf_token %}
                    <div class="col-md-6">
                        <div class="billing-details">

                            <div class="section-title">
                                <h4 class="title">Shipping Details</h4>
                            </div>
                            <p><label for="id_first_name">First name:</label>
                                <input type="text" name="first_name"  value="{{user.first_name}}" class="input" maxlength="10" required id="id_first_name"></p>
                            <p><label for="id_last_name">Last name:</label>
                                <input type="text" name="last_name"  value="{{user.last_name}}" class="input" maxlength="10" required id="id_last_name"></p>
                            <p><label for="id_address">Address:</label>
                                <input type="text" name="address" value="{{profile.address}}" class="input" maxlength="150" id="id_address"></p>
                            <p><label for="id_phone">Phone:</label>
                                <input type="text" name="phone"  value="{{profile.phone}}"  class="input" maxlength="20" id="id_phone"></p>
                            <p><label for="id_city">City:</label>
                                <select name="city" class="input" id="id_city">
                                    <option value="{{profile.city}}" selected>{{profile.city}}</option>
                                    <option value="İstanbul">Istanbul</option>
                                    <option value="Ankara">Ankara</option>
                                    <option value="İzmir">Izmir</option>
                                    <option value="Bursa">Bursa</option>
                                    <option value="Konya">Konya</option>
                                    <option value="Yozgat">Yozgat</option>
                                </select></p>
                            <p><label for="id_first_name">Country :</label>
                                <input type="text" name="country" class="input" id="id_country" value="{{profile.country}}"></p>
                            <div class="pull-right">
                                <button  type="submit" class="primary-btn">Complete Order</button>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="shiping-methods">
                            <div class="section-title">
                                <h4 class="title">Payment Information</h4>
                            </div>
                            <p><label for="id_first_name">Total: {{total}} USD </label>
                                <input type="text" name="total" class="input" readonly value="{{total}}"></p>
                            <p><label for="id_first_name">Credit Card Holder</label>
                                <input type="text" name="holder" class="input"  value=""></p>
                            <p><label for="id_first_name">Credit Card Number</label>
                                <input type="text" name="number" class="input"  value=""></p>
                            <p><label for="id_first_name">Credit Exp Date/Year</label>
                                <input type="text" name="ecpdate" class="input"  placeholder="mm/yy"></p>
                            <p><label for="id_first_name">Security Number</label>
                                <input type="text" name="secnumber" class="input"  value=""></p>
                        </div>
                    </div>

                </Form>

                <div class="col-md-12">
                    <div class="order-summary clearfix">
                        <div class="section-title">
                            <h3 class="title">Shopcart Product List</h3>
                        </div>
                                                <table class="shopping-cart-table table">
                            <thead>
                            <tr>
                                <th></th>
                                <th>Product</th>
                                <th class="text-center">Price</th>
                                <th class="text-center">Quantity</th>
                                <th class="text-center">Total</th>
                                <th class="text-right"></th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for k in shopcart %}
                                <tr>
                                    <td class="thumb">
                                            <img src="{{k.product.image.url}}" alt="">
                                            <img src="" alt="">
                                    </td>
                                    <td class="details">
                                        <a href="">
                                            {{k.product}}
                                        </a>  
                                    </td>
                                    <td class="price text-center">
                                        <strong>{{k.price}}</strong>
                                    </td>
                                    <td class="qty text-center">
                                        <strong>{{k.quantity}}</strong>
                                    </td>
                                    <td class="total text-center">
                                        <strong class="primary-color">${{k.amount}}</strong>
                                    </td>
                                    <td class="text-right"><a href="" onclick="return confirm('Delete ! Are you sure?')" class="main-btn icon-btn"><i class="fa fa-close"></i></a></td>
                                </tr>

                            {% endfor %}

                            </tbody>
                            <tfoot>
                            <tr>
                                <th class="empty" colspan="3"></th>
                                <th>SUBTOTAL</th>
                                <th colspan="2" class="sub-total">{{total}}</th>
                            </tr>
                            <tr>
                                <th class="empty" colspan="3"></th>
                                <th>SHIPING</th>
                                <td colspan="2">Free Shipping</td>
                            </tr>
                            <tr>
                                <th class="empty" colspan="3"></th>
                                <th>TOTAL</th>
                                <th colspan="2" class="total">{{total}}</th>
                            </tr>
                            </tfoot>
                        </table>

                    </div>

                </div>


            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock %}